name: Deploy to Azure

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1.0.0
      name: Checkout repository

    - uses: actions/setup-node@v1.1.2
      name: Setup Node.js 10.x
      with:
        version: 10.x

    - run: npm install

    - run: npm run build --if-present

    - run: npm run test --if-present

    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: GaymersBot
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}